import type { Metadata } from "next";
import "./globals.css";
import Nav from "./_components/nav";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "MusicNerd",
  description: "Generated by create next app",
};

export default async  function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en"> 
      <body>
          <Nav/>
          {children}
          <Toaster/>
      </body>
    </html>
  );
}
