import type { Metadata } from "next";
import "./globals.css";
import Nav from "./_components/nav";
import type { Session } from 'next-auth';

export const metadata: Metadata = {
  title: "MusicNerd",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  pageProps
}: {
  children: React.ReactNode;
  pageProps: Session;

}) {
  return (
    <html lang="en"> 
      <body>
          <Nav session={pageProps}/>
          {children}
      </body>
    </html>
  );
}
