/**
 * A curated, real subset of a 300-post Apify `instagram-scraper` run against
 * the test artist (Pete Rango / p3t3rango) — extracted with `mapApifyPost` (see
 * socialIngest.ts) from the raw scrape backed up at `/tmp/ig-deep.json` (not
 * committed; ~5MB). Every field below is real: real captions, real handles,
 * real engagement counts, real timestamps. This file only curates WHICH of the
 * 300 posts to include, not their content — see
 * `.superpowers/sdd/2026-08-17-post-claim-onboarding/apify-validation-findings.md`.
 *
 * Composition (why these posts, not others):
 * - 6 posts authored by @dameatlas (a real collaborator — "crying on the floor")
 *   including the "house been therapy" outlier from the validation findings doc.
 * - 1 own post that tags @dameatlas as a coauthor (tests the two collaborator
 *   detection paths — coauthors AND foreign owner — converging on one handle).
 * - 2 posts each from @liv.corp, @rein.rocks, @deadsetfc, @soft_core.music —
 *   lower-ranked real collaborators/coauthors.
 * - 3 own posts sharing the real "midjourney" hashtag (recurring theme).
 * - 8 own posts carrying real track credits (musicInfo survived the noise filter).
 * - 2 own posts with real above-baseline likeCount (standout candidates).
 * - 4 own posts from June 2018 (a real posting cluster — burst candidate).
 */
import type { SocialPostRow } from "../socialSignals";

export const IG_FIXTURE_POSTS: SocialPostRow[] = [
    {
        platform: "instagram",
        platformPostId: "3892673739275672320",
        ownerUsername: "dameatlas",
        isOwnPost: false,
        caption: "this ones really special .. \n\n#housemusiclovers #musiclover #housemusic",
        url: "https://www.instagram.com/p/DYFjiRABJsA/",
        postedAt: "2026-05-08T17:57:53.000Z",
        likeCount: 214,
        commentCount: 24,
        playCount: 5231,
        hashtags: ["housemusiclovers", "musiclover", "housemusic"],
        mentions: ["pressurefiles"],
        coauthors: [],
        musicTitle: null,
        musicArtist: null,
    },
    {
        platform: "instagram",
        platformPostId: "3897777145489253380",
        ownerUsername: "dameatlas",
        isOwnPost: false,
        caption: "crying on the floor… go run that \n\n#housemusic #housemusiclovers #housemusicdj #newmusic #singer",
        url: "https://www.instagram.com/p/DYXr6maheQE/",
        postedAt: "2026-05-15T18:57:58.000Z",
        likeCount: 104,
        commentCount: 3,
        playCount: 3977,
        hashtags: ["housemusic", "housemusiclovers", "housemusicdj", "newmusic", "singer"],
        mentions: [],
        coauthors: [],
        musicTitle: "crying on the floor (pete rango mix)",
        musicArtist: "Dame Atlas, Pete Rango",
    },
    {
        platform: "instagram",
        platformPostId: "3897922229912402163",
        ownerUsername: "dameatlas",
        isOwnPost: false,
        caption: "@dameatlas “crying on the floor” performance \n\n#housemusic #housemusiclovers #fyp #dameatlas",
        url: "https://www.instagram.com/p/DYYM520Bvjz/",
        postedAt: "2026-05-15T23:48:06.000Z",
        likeCount: 156,
        commentCount: 9,
        playCount: 4676,
        hashtags: ["housemusic", "housemusiclovers", "fyp", "dameatlas"],
        mentions: ["dameatlas", "pressurefiles"],
        coauthors: [],
        musicTitle: null,
        musicArtist: null,
    },
    {
        platform: "instagram",
        platformPostId: "3897639020708278887",
        ownerUsername: "dameatlas",
        isOwnPost: false,
        caption: "crying on the floor // out now w/ @p3t3rango 🦇 \n\n#housemusiclovers #housemusic #fyp #viral #newmusic",
        url: "https://www.instagram.com/p/DYXMgnsBLJn/",
        postedAt: "2026-05-15T14:22:36.000Z",
        likeCount: 300,
        commentCount: 6,
        playCount: 6066,
        hashtags: ["housemusiclovers", "housemusic", "fyp", "viral", "newmusic"],
        mentions: [],
        coauthors: [],
        musicTitle: "crying on the floor (pete rango mix)",
        musicArtist: "Dame Atlas, Pete Rango",
    },
    {
        platform: "instagram",
        platformPostId: "3900667942719119691",
        ownerUsername: "dameatlas",
        isOwnPost: false,
        caption: "house is a black church on a tuesday night 🌹 #blackhouse #housemusic #housemusiclover #soulhouse",
        url: "https://www.instagram.com/p/DYh9NPIhuFL/",
        postedAt: "2026-05-19T18:42:35.000Z",
        likeCount: 499,
        commentCount: 19,
        playCount: 8285,
        hashtags: ["blackhouse", "housemusic", "housemusiclover", "soulhouse"],
        mentions: ["pressurefiles"],
        coauthors: [],
        musicTitle: "crying on the floor (pete rango mix)",
        musicArtist: "Dame Atlas, Pete Rango",
    },
    {
        platform: "instagram",
        platformPostId: "3898329782420846497",
        ownerUsername: "dameatlas",
        isOwnPost: false,
        caption: "house been therapy fr 🤍 #blackhouse #househeads #soulhouse #housemusic #housemusiclover",
        url: "https://www.instagram.com/p/DYZpkhqhTeh/",
        postedAt: "2026-05-16T13:14:10.000Z",
        likeCount: 794,
        commentCount: 14,
        playCount: 16366,
        hashtags: ["blackhouse", "househeads", "soulhouse", "housemusic", "housemusiclover"],
        mentions: ["pressurefiles"],
        coauthors: [],
        musicTitle: null,
        musicArtist: null,
    },
    {
        platform: "instagram",
        platformPostId: "3859255569744569499",
        ownerUsername: "p3t3rango",
        isOwnPost: true,
        caption: "“I loved you more than I loved myself…”\n\n@dameatlas - love you more (@p3t3rango mix) out now",
        url: "https://www.instagram.com/p/DWO1H5UEqSb/",
        postedAt: "2026-03-23T15:23:34.000Z",
        likeCount: 102,
        commentCount: 7,
        playCount: 3609,
        hashtags: [],
        mentions: ["dameatlas"],
        coauthors: ["dameatlas"],
        musicTitle: null,
        musicArtist: null,
    },
    {
        platform: "instagram",
        platformPostId: "3352701710962718189",
        ownerUsername: "liv.corp",
        isOwnPost: false,
        caption: "SYNC TIP: Make sure you have high quality music. A bad mix or portly arranged track can ruin your chances of getting sync placements. Make sure invest your time/money in making sure your tracks are ready for commercial use.\n\n@devinsnorris x @p3t3rango",
        url: "https://www.instagram.com/p/C6HMHFXxvXt/",
        postedAt: "2024-04-23T17:30:30.000Z",
        likeCount: 54,
        commentCount: 6,
        playCount: 1502,
        hashtags: [],
        mentions: ["devinsnorris", "chereleworld"],
        coauthors: [],
        musicTitle: null,
        musicArtist: null,
    },
    {
        platform: "instagram",
        platformPostId: "2963479601005506680",
        ownerUsername: "liv.corp",
        isOwnPost: false,
        caption: "A few weeks ago we got the chance to setup a mobile Dream Lab experience at Artober Fest presented by @cultureworksrva. Here, festival attendees got a chance to create music with our mentors, create AI art, and learn more about our Dream Lab program we are developing in Petersburg, VA.\n\nShout out to everyone that stopped by to collaborate with us! \nYou can find the full vlog and demos we created in the link in our bio\n\nCollaborators: Meshell, @wordsnsuch217, @nicklubymusic, @babyjake_and_thedolls , & @thisisdjack \n\nLIV Mentors: @lil_vibeee, @phillipbrges, @hazelgrovvve, @p3t3rango",
        url: "https://www.instagram.com/p/CkgZP71DLB4/",
        postedAt: "2022-11-03T16:58:46.000Z",
        likeCount: 69,
        commentCount: 7,
        playCount: 1831,
        hashtags: [],
        mentions: ["cultureworksrva", "wordsnsuch217", "nicklubymusic", "babyjake_and_thedolls", "thisisdjack", "lil_vibeee", "phillipbrges", "hazelgrovvve", "hazelgrove.mp3", "per.ily", "artoberva"],
        coauthors: [],
        musicTitle: null,
        musicArtist: null,
    },
    {
        platform: "instagram",
        platformPostId: "3235985232292845359",
        ownerUsername: "rein.rocks",
        isOwnPost: false,
        caption: "📻PRE-SAVE IN BIO!!\nSo excited to share this one with you 💜\n#independentartist #newmusicfriday #rein",
        url: "https://www.instagram.com/p/Czoh2x9OZcv/",
        postedAt: "2023-11-14T16:42:20.000Z",
        likeCount: -1,
        commentCount: 16,
        playCount: 6733,
        hashtags: ["independentartist", "newmusicfriday", "rein"],
        mentions: ["romesempire", "parker.reinecke", "loschafin", "weterpellman", "thomas_prest0n", "go_alan_go_", "shockoe_records"],
        coauthors: ["go_alan_go_", "shockoe_records", "thomas_prest0n"],
        musicTitle: null,
        musicArtist: null,
    },
    {
        platform: "instagram",
        platformPostId: "3156198186343182836",
        ownerUsername: "rein.rocks",
        isOwnPost: false,
        caption: "@p3t3rango and I are #lettingitgo for the Evermore release TOMORROW!!!!! Pre-Save in bio!💜♾️\n#newmusic #indierock #indiepop #newrock #newmusicfriday",
        url: "https://www.instagram.com/p/CvNEYc5t7H0/",
        postedAt: "2023-07-27T14:33:12.000Z",
        likeCount: -1,
        commentCount: 1,
        playCount: 2522,
        hashtags: ["lettingitgo", "newmusic", "indierock", "indiepop", "newrock", "newmusicfriday"],
        mentions: [],
        coauthors: [],
        musicTitle: null,
        musicArtist: null,
    },
    {
        platform: "instagram",
        platformPostId: "3590424247727125593",
        ownerUsername: "deadsetfc",
        isOwnPost: false,
        caption: "Destino is a personal and cultural exploration of Colombian identity through the lens of football, fashion, and music—documenting Richmond-based producer @p3t3rango journey to reconnect with his family history and highlighting how his heritage shapes his work as a music producer and creative director. \n\nVisit the link in our bio for more about Destino⚽️🇨🇴❤️\n\n#staydeadset #destino",
        url: "https://www.instagram.com/p/DHTv9SWuXRZ/",
        postedAt: "2025-03-17T17:19:38.000Z",
        likeCount: 136,
        commentCount: 33,
        playCount: 6184,
        hashtags: ["staydeadset", "destino"],
        mentions: ["rvamag", "kevaux__", "ricardopava", "belabucatini", "boteropaula5"],
        coauthors: ["kevaux__", "rvamag"],
        musicTitle: null,
        musicArtist: null,
    },
    {
        platform: "instagram",
        platformPostId: "3821810323204091738",
        ownerUsername: "deadsetfc",
        isOwnPost: false,
        caption: "Dead Set x Bela Bucatini — qué flow pues \n\nHailing from the streets of Medellín, Bela is a hip-hop force with football in her veins. Dead Set FC’s @p3t3rango sat down with her and chopped about life, music, football, and how the beautiful game keeps her pushing towards something bigger. Full interview drops this week.\n\nTalent: @belabucatini \nDir: @p3t3rango @kevaux__ \nCam: @p3t3rango \nVideo + Photo: @pezrosadito \nEdit: @nawtcreative @kevaux__ \nMUA: @blueconpielazul \n\n#staydeadset",
        url: "https://www.instagram.com/p/DUJzD15gC9a/",
        postedAt: "2026-01-30T23:32:15.000Z",
        likeCount: 30,
        commentCount: 2,
        playCount: 1460,
        hashtags: ["staydeadset"],
        mentions: ["belabucatini", "kevaux__", "pezrosadito", "nawtcreative", "blueconpielazul"],
        coauthors: ["kevaux__"],
        musicTitle: null,
        musicArtist: null,
    },
    {
        platform: "instagram",
        platformPostId: "3944108346453556938",
        ownerUsername: "soft_core.music",
        isOwnPost: false,
        caption: "debut single blindside streaming everywhere.",
        url: "https://www.instagram.com/p/Da8SaTyBH7K/",
        postedAt: "2026-07-18T17:07:55.000Z",
        likeCount: 26,
        commentCount: 1,
        playCount: 952,
        hashtags: [],
        mentions: ["dear_rod"],
        coauthors: ["dear_rod"],
        musicTitle: null,
        musicArtist: null,
    },
    {
        platform: "instagram",
        platformPostId: "3911373215293190695",
        ownerUsername: "soft_core.music",
        isOwnPost: false,
        caption: "waxy",
        url: "https://www.instagram.com/p/DZH_TdJhzIn/",
        postedAt: "2026-06-03T13:08:06.000Z",
        likeCount: 31,
        commentCount: 0,
        playCount: null,
        hashtags: [],
        mentions: ["dear_rod"],
        coauthors: ["dear_rod"],
        musicTitle: null,
        musicArtist: null,
    },
    {
        platform: "instagram",
        platformPostId: "3133360041466300807",
        ownerUsername: "p3t3rango",
        isOwnPost: true,
        caption: "Pearled flowercore \n\n#midjourney #ai",
        url: "https://www.instagram.com/p/Ct77ltBAImH/",
        postedAt: "2023-06-26T02:14:18.000Z",
        likeCount: 42,
        commentCount: 2,
        playCount: 1059,
        hashtags: ["midjourney", "ai"],
        mentions: [],
        coauthors: [],
        musicTitle: "The Difference (Extended) (feat. Toro y Moi)",
        musicArtist: "Flume",
    },
    {
        platform: "instagram",
        platformPostId: "3135661356523601593",
        ownerUsername: "p3t3rango",
        isOwnPost: true,
        caption: "Pastel Yarn Jungles\n#midjourney #aiart #midjourneyzoom",
        url: "https://www.instagram.com/p/CuEG2Prgj65/",
        postedAt: "2023-06-29T06:28:29.000Z",
        likeCount: 80,
        commentCount: 5,
        playCount: 2479,
        hashtags: ["midjourney", "aiart", "midjourneyzoom"],
        mentions: [],
        coauthors: [],
        musicTitle: "Stage Five (Instrumental)",
        musicArtist: "Vault 49",
    },
    {
        platform: "instagram",
        platformPostId: "2949730604134145901",
        ownerUsername: "p3t3rango",
        isOwnPost: true,
        caption: "MidJourney to blender exercise 🤘\n\n#3d #midjourney #characterdesign #c4d",
        url: "https://www.instagram.com/p/CjvjFsqg59t/",
        postedAt: "2022-10-15T17:36:34.000Z",
        likeCount: 61,
        commentCount: 4,
        playCount: 803,
        hashtags: ["3d", "midjourney", "characterdesign", "c4d"],
        mentions: [],
        coauthors: [],
        musicTitle: "Monkeys Spinning Monkeys",
        musicArtist: "Kevin MacLeod, Kevin",
    },
    {
        platform: "instagram",
        platformPostId: "3964250912436267844",
        ownerUsername: "p3t3rango",
        isOwnPost: true,
        caption: "If you’ve seen what’s happening in Colombia and wanted to help, I made something that might make it easier.\n\nOn August 10, a 7.4-magnitude earthquake struck western Colombia, devastating communities including Cali and Pereira. Hundreds of people have died, thousands have been injured, and thousands of homes have been destroyed.\n\nI put together a simple bilingual page with vetted charities, official relief agencies, blood donation sites, and supply drop-off locations. The link is in my bio. If you can’t donate, sharing it still helps.\n\nhelp-Colombia.com\n\n#colombia #earthquake #colombiaearthquake",
        url: "https://www.instagram.com/p/DcD2TOMSCtE/",
        postedAt: "2026-08-15T12:10:33.000Z",
        likeCount: 214,
        commentCount: 19,
        playCount: 8144,
        hashtags: ["colombia", "earthquake", "colombiaearthquake"],
        mentions: ["valen_garces", "colomborkrdz", "soylauvalencia", "luzharias"],
        coauthors: [],
        musicTitle: "Signals",
        musicArtist: "Brian Eno",
    },
    {
        platform: "instagram",
        platformPostId: "3858469471166568319",
        ownerUsername: "p3t3rango",
        isOwnPost: true,
        caption: "New vlog series loading for @deadsetfc 📹We spent the day at Church Hill Irish Festival and the Kickers opener just soaking it in and talking to the people who make RVA so special.",
        url: "https://www.instagram.com/p/DWMCYp9kpd_/",
        postedAt: "2026-03-22T13:18:07.000Z",
        likeCount: 27,
        commentCount: 2,
        playCount: 1853,
        hashtags: [],
        mentions: ["deadsetfc", "richmondkickers", "kevaux__", "rivercityredarmy", "churchhill_irishfestival", "uvdave", "dear_rod"],
        coauthors: [],
        musicTitle: "When I Rest I Rust",
        musicArtist: "Down to Nothing",
    },
    {
        platform: "instagram",
        platformPostId: "3843244979955623767",
        ownerUsername: "p3t3rango",
        isOwnPost: true,
        caption: "“rush” out now exclusively on @subvertworld \n\nAssistant producer: @soothebyhendrix \nMix & Master by: @p3t3rango",
        url: "https://www.instagram.com/p/DVV8vJnDudX/",
        postedAt: "2026-03-01T13:14:24.000Z",
        likeCount: 45,
        commentCount: 9,
        playCount: 1687,
        hashtags: [],
        mentions: ["subvertworld", "soothebyhendrix", "xuerecords"],
        coauthors: ["soothebyhendrix", "xuerecords"],
        musicTitle: "rush",
        musicArtist: "Pete Rango",
    },
    {
        platform: "instagram",
        platformPostId: "3480830102773077809",
        ownerUsername: "p3t3rango",
        isOwnPost: true,
        caption: "The true self lies beneath the woven tales.\n🔺 @lilxlil 🔺\n\n11/01\n\nPRE-SAVE LINK IN BIO",
        url: "https://www.instagram.com/p/DBOZIlHRpcx/",
        postedAt: "2024-10-17T12:15:32.000Z",
        likeCount: 88,
        commentCount: 15,
        playCount: 2870,
        hashtags: [],
        mentions: ["lilxlil", "whoisoyabun", "hellz_own"],
        coauthors: ["lilxlil"],
        musicTitle: "OFF THE LEASH",
        musicArtist: "LIL LIL, Pete Rango",
    },
    {
        platform: "instagram",
        platformPostId: "3493183458921196948",
        ownerUsername: "p3t3rango",
        isOwnPost: true,
        caption: "Reminiscing about that time Mom taught us how to make empanadas. \n\nGolden, crispy, and packed with flavor – these 🇨🇴 Colombian empanadas are a bite of tradition you can’t resist. Perfectly seasoned beef and potato filling wrapped in a crunchy corn shell, served with a side of ají sauce 🇨🇴✨\n\nDough:\n\n\t•\t2 cups cornmeal (preferably yellow, precooked cornmeal like pan or masarepa)\n\t•\t2 ½ cups warm water\n\t•\t1 teaspoon salt\n\t•\t1 tablespoon vegetable oil\n\nFilling:\n\n\t•\t1 lb flank steak, ground beef or shredded chicken (optional for vegetarian: mashed potatoes or cheese)\n\t•\t3 medium potatoes, peeled and diced \n\t•\t1 medium onion, finely chopped\n\t•\t2 cloves garlic, minced\n\t•\t1 small bell pepper, finely chopped\n\t•\t1 teaspoon ground cumin\n\t•\t½ teaspoon paprika\n\t•\tSalt and black pepper to taste\n\t•\t1 tablespoon vegetable oil for sautéing\n\t•\tFresh cilantro, chopped (optional)\n •  1 cubito de Knorr Caldo con Sabor de  Pollo \n\nAccompaniments:\n\n\t•\tAjí sauce (for dipping)\n\t•\tLime wedges (optional)",
        url: "https://www.instagram.com/p/DB6R9kkRK2U/",
        postedAt: "2024-11-03T13:32:58.000Z",
        likeCount: 99,
        commentCount: 3,
        playCount: 1582,
        hashtags: [],
        mentions: ["xtinaellisisland", "luzharias"],
        coauthors: [],
        musicTitle: "Las Empanadas",
        musicArtist: "Los Caracuchos",
    },
    {
        platform: "instagram",
        platformPostId: "2959068468927792005",
        ownerUsername: "p3t3rango",
        isOwnPost: true,
        caption: "🐺SAVAGE PLANET🐺 IS OUT NOW! Link in bio\nSavage Planet is a sonic journey into the wild. An introduction to a world with no rules - a world where instincts subjugate convention and imagination is your only compass. \n\nThis concept was spurred from a moment in both producers’ lives where they simultaneously felt inspired to let go of the traditional pop structure they were so used to adhering to. Instead, they chose to create music that mirrored a free flow of consciousness that came about as a direct result of the inspiration they felt when creating this music. As a result, most of the project was created in one night.\n\nCreative direction & production: @p3t3rango & @producedbyxmane \n3D pixel mover: @nawtcreative \nMixed and mastered: @p3t3rango \nDistro: @venicemusic.co \n\n#3d #newmusic #newmusicfriday #halloween #brainfeeder #warprecords \n#savageplanet #leplanetesauvage",
        url: "https://www.instagram.com/p/CkQuRg8gAOF/",
        postedAt: "2022-10-28T14:56:15.000Z",
        likeCount: 71,
        commentCount: 9,
        playCount: 1716,
        hashtags: ["3d", "newmusic", "newmusicfriday", "halloween", "brainfeeder", "warprecords", "savageplanet", "leplanetesauvage"],
        mentions: ["producedbyxmane", "nawtcreative", "venicemusic.co", "warprecords", "kevintheodoreofficial", "brainfeederrecords", "venicemusic"],
        coauthors: ["kevintheodoreofficial"],
        musicTitle: "Planet X",
        musicArtist: "Pete Rango, Xmane",
    },
    {
        platform: "instagram",
        platformPostId: "2949293057327829269",
        ownerUsername: "p3t3rango",
        isOwnPost: true,
        caption: "",
        url: "https://www.instagram.com/p/Cjt_mjcjREV/",
        postedAt: "2022-10-15T03:06:02.000Z",
        likeCount: 34,
        commentCount: 0,
        playCount: 702,
        hashtags: [],
        mentions: [],
        coauthors: [],
        musicTitle: "LSD DREAMZ",
        musicArtist: "oseanworld",
    },
    {
        platform: "instagram",
        platformPostId: "3272249636773294955",
        ownerUsername: "p3t3rango",
        isOwnPost: true,
        caption: "I’ve been working. Just in case you were curious 🤘💜🕺",
        url: "https://www.instagram.com/p/C1pXbUgRfNr/",
        postedAt: "2024-01-03T17:23:29.000Z",
        likeCount: 51,
        commentCount: 10,
        playCount: 1013,
        hashtags: [],
        mentions: [],
        coauthors: [],
        musicTitle: "Dreamvibe",
        musicArtist: "Pete Rango, Elle Symone",
    },
    {
        platform: "instagram",
        platformPostId: "2361110132605270565",
        ownerUsername: "p3t3rango",
        isOwnPost: true,
        caption: "“Insert long post about growth and happiness here.”\n\nBut for real, 2020 has forced me to grow in a lot of ways. I’m so grateful to be alive and breathing. \n\nThank you @nickmarfing for the rad pics",
        url: "https://www.instagram.com/p/CDEWSfpgzol/",
        postedAt: "2020-07-25T14:11:23.000Z",
        likeCount: 410,
        commentCount: 33,
        playCount: null,
        hashtags: [],
        mentions: ["nickmarfing"],
        coauthors: [],
        musicTitle: null,
        musicArtist: null,
    },
    {
        platform: "instagram",
        platformPostId: "2480133569667046444",
        ownerUsername: "p3t3rango",
        isOwnPost: true,
        caption: "#notcreative",
        url: "https://www.instagram.com/p/CJrNFdfhpws/",
        postedAt: "2021-01-05T19:33:58.000Z",
        likeCount: 377,
        commentCount: 60,
        playCount: null,
        hashtags: ["notcreative"],
        mentions: [],
        coauthors: [],
        musicTitle: null,
        musicArtist: null,
    },
    {
        platform: "instagram",
        platformPostId: "1793106490926349784",
        ownerUsername: "p3t3rango",
        isOwnPost: true,
        caption: "Philly tonight ... @whoisoyabun opening up for @travisscott 🗡💫 @sevenrecs 🤟🤟🤟🔥🔥🔥",
        url: "https://www.instagram.com/p/BjiZNpsHL3Y/",
        postedAt: "2018-06-02T21:29:32.000Z",
        likeCount: 36,
        commentCount: 1,
        playCount: null,
        hashtags: [],
        mentions: ["whoisoyabun", "travisscott", "sevenrecs"],
        coauthors: [],
        musicTitle: null,
        musicArtist: null,
    },
    {
        platform: "instagram",
        platformPostId: "1796125193481864113",
        ownerUsername: "p3t3rango",
        isOwnPost: true,
        caption: "First stop on the HEAVEN ON EARTH TOUR👼🏾🌍 “DREAMLAND” curated by @untitledny and @whoisoyabun...this will also be @sevenrecs new signee @tayloreve debut performance!!! 10p sharppp",
        url: "https://www.instagram.com/p/BjtHljhncOx/",
        postedAt: "2018-06-07T01:27:09.000Z",
        likeCount: 33,
        commentCount: 2,
        playCount: null,
        hashtags: [],
        mentions: ["untitledny", "whoisoyabun", "sevenrecs", "tayloreve", "_.kinida._", "baker.wm", "brianamulzac", "mgspnewyork", "poster.boy", "milkookiemilk"],
        coauthors: [],
        musicTitle: null,
        musicArtist: null,
    },
    {
        platform: "instagram",
        platformPostId: "1797294426681081417",
        ownerUsername: "p3t3rango",
        isOwnPost: true,
        caption: "@majorstage x @houseofmau x TSK EP debut single #Nostalgic out now urrywhere in collaboration with @michaelfromtheeast x @jaetips 🕺(prod. by myself @zavodskyalan @parrispierce) SPECIAL THANKS TO @alexpsaroudakis FOR MASTERING THE TRACK!!!",
        url: "https://www.instagram.com/p/BjxRcIzHX5J/",
        postedAt: "2018-06-08T16:12:53.000Z",
        likeCount: 40,
        commentCount: 7,
        playCount: null,
        hashtags: ["Nostalgic"],
        mentions: ["majorstage", "houseofmau", "michaelfromtheeast", "jaetips", "zavodskyalan", "parrispierce", "alexpsaroudakis"],
        coauthors: [],
        musicTitle: null,
        musicArtist: null,
    },
    {
        platform: "instagram",
        platformPostId: "1807045756635185872",
        ownerUsername: "p3t3rango",
        isOwnPost: true,
        caption: "@tayloreve debut single “Like You” ft. @whoisoyabun prod. by @silasbijan is out now on all platforms!!!! Thank you to everyone that has been supporting and sharing the song!!!! @snoopdogg approved 🕺@sevenrecs mastered by: @sterlingsound",
        url: "https://www.instagram.com/p/BkT6oqhHgLQ/",
        postedAt: "2018-06-22T03:04:22.000Z",
        likeCount: 55,
        commentCount: 4,
        playCount: null,
        hashtags: [],
        mentions: ["tayloreve", "whoisoyabun", "silasbijan", "snoopdogg", "sevenrecs", "sterlingsound"],
        coauthors: [],
        musicTitle: null,
        musicArtist: null,
    },
];
