name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_SPOTIFY_WEB_CLIENT_ID: ${{ secrets.SPOTIFY_WEB_CLIENT_ID }}
      NEXT_PUBLIC_SPOTIFY_WEB_CLIENT_SECRET: ${{ secrets.SPOTIFY_WEB_CLIENT_SECRET }}
      NEXTAUTH_SECRET: test-secret-for-ci
      NEXTAUTH_URL: http://localhost:3000
      SUPABASE_DB_CONNECTION: ${{ secrets.SUPABASE_DB_CONNECTION }}
      DISCORD_COVERAGE_URL: ${{ secrets.DISCORD_COVERAGE_URL }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Type check
      run: npm run type-check || npm run tsc

    - name: Lint
      run: npm run lint

    - name: Run tests (without coverage)
      run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test

    env:
      NEXT_PUBLIC_SPOTIFY_WEB_CLIENT_ID: ${{ secrets.SPOTIFY_WEB_CLIENT_ID }}
      NEXT_PUBLIC_SPOTIFY_WEB_CLIENT_SECRET: ${{ secrets.SPOTIFY_WEB_CLIENT_SECRET }}
      NEXTAUTH_SECRET: test-secret-for-ci
      NEXTAUTH_URL: http://localhost:3000
      SUPABASE_DB_CONNECTION: ${{ secrets.SUPABASE_DB_CONNECTION }}
      DISCORD_COVERAGE_URL: ${{ secrets.DISCORD_COVERAGE_URL }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: .next/
        retention-days: 14

  coverage:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/staging'

    env:
      NEXT_PUBLIC_SPOTIFY_WEB_CLIENT_ID: ${{ secrets.SPOTIFY_WEB_CLIENT_ID }}
      NEXT_PUBLIC_SPOTIFY_WEB_CLIENT_SECRET: ${{ secrets.SPOTIFY_WEB_CLIENT_SECRET }}
      NEXTAUTH_SECRET: test-secret-for-ci
      NEXTAUTH_URL: http://localhost:3000
      SUPABASE_DB_CONNECTION: ${{ secrets.SUPABASE_DB_CONNECTION }}
      DISCORD_COVERAGE_URL: ${{ secrets.DISCORD_COVERAGE_URL }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests with coverage
      run: npm test -- --coverage

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload test coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage/
        retention-days: 14

    - name: Send coverage webhook
      if: always()
      run: |
        # Parse coverage summary
        if [ -f coverage/coverage-summary.json ]; then
          COVERAGE_DATA=$(cat coverage/coverage-summary.json)
          echo "Coverage data found:"
          echo "$COVERAGE_DATA" | head -20
          
          # Send to Discord if configured
          if [ -n "${{ secrets.DISCORD_COVERAGE_URL }}" ]; then
            # Extract coverage percentages
            LINES_PCT=$(echo "$COVERAGE_DATA" | jq -r '.total.lines.pct // 0')
            FUNCTIONS_PCT=$(echo "$COVERAGE_DATA" | jq -r '.total.functions.pct // 0')
            BRANCHES_PCT=$(echo "$COVERAGE_DATA" | jq -r '.total.branches.pct // 0')
            
            echo "Extracted coverage: Lines=$LINES_PCT%, Functions=$FUNCTIONS_PCT%, Branches=$BRANCHES_PCT%"
            
            # Determine color based on line coverage
            if (( $(echo "$LINES_PCT >= 80" | bc -l) )); then
              COLOR=65280  # Green
            elif (( $(echo "$LINES_PCT >= 60" | bc -l) )); then
              COLOR=16776960  # Yellow
            else
              COLOR=16711680  # Red
            fi
            
            echo "Sending Discord webhook to: ${{ secrets.DISCORD_COVERAGE_URL }}"
            WEBHOOK_RESPONSE=$(curl -s -w "%{http_code}" -X POST "${{ secrets.DISCORD_COVERAGE_URL }}" \
              -H "Content-Type: application/json" \
              -d "{
                \"embeds\": [{
                  \"title\": \"Coverage Report: ${{ github.repository }}\",
                  \"description\": \"Branch: ${{ github.ref_name }}\\nCommit: ${GITHUB_SHA:0:7}\",
                  \"color\": $COLOR,
                  \"fields\": [
                    {\"name\": \"Lines\", \"value\": \"${LINES_PCT}%\", \"inline\": true},
                    {\"name\": \"Functions\", \"value\": \"${FUNCTIONS_PCT}%\", \"inline\": true},
                    {\"name\": \"Branches\", \"value\": \"${BRANCHES_PCT}%\", \"inline\": true}
                  ],
                  \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"
                }]
              }")
            echo "Discord webhook response: $WEBHOOK_RESPONSE"
          fi
        else
          echo "Coverage summary file not found!"
          # Send a failure notification to Discord if configured
          if [ -n "${{ secrets.DISCORD_COVERAGE_URL }}" ]; then
            curl -X POST "${{ secrets.DISCORD_COVERAGE_URL }}" \
              -H "Content-Type: application/json" \
              -d "{
                \"embeds\": [{
                  \"title\": \"❌ Coverage Report Failed: ${{ github.repository }}\",
                  \"description\": \"Branch: ${{ github.ref_name }}\\nCommit: ${GITHUB_SHA:0:7}\\n\\nCoverage data not generated!\",
                  \"color\": 16711680,
                  \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"
                }]
              }"
          fi
        fi

    # Add a status check summary
    - name: Check Status
      if: always()
      run: |
        STATUS="${{ job.status }}"
        echo "Current job status: $STATUS"
        if [ "$STATUS" = "success" ]; then
          echo "✅ All checks passed!"
          exit 0
        else
          echo "❌ Some checks failed!"
          echo "Job status was: $STATUS"
          exit 1 