name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_SPOTIFY_WEB_CLIENT_ID: ${{ secrets.SPOTIFY_WEB_CLIENT_ID }}
      NEXT_PUBLIC_SPOTIFY_WEB_CLIENT_SECRET: ${{ secrets.SPOTIFY_WEB_CLIENT_SECRET }}
      NEXTAUTH_SECRET: test-secret-for-ci
      NEXTAUTH_URL: http://localhost:3000
      SUPABASE_DB_CONNECTION: ${{ secrets.SUPABASE_DB_CONNECTION }}
      DISCORD_COVERAGE_URL: ${{ secrets.DISCORD_COVERAGE_URL }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Type check
      run: npm run type-check || npm run tsc

    - name: Lint
      run: npm run lint

    - name: Run tests (without coverage)
      run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test

    env:
      NEXT_PUBLIC_SPOTIFY_WEB_CLIENT_ID: ${{ secrets.SPOTIFY_WEB_CLIENT_ID }}
      NEXT_PUBLIC_SPOTIFY_WEB_CLIENT_SECRET: ${{ secrets.SPOTIFY_WEB_CLIENT_SECRET }}
      NEXTAUTH_SECRET: test-secret-for-ci
      NEXTAUTH_URL: http://localhost:3000
      SUPABASE_DB_CONNECTION: ${{ secrets.SUPABASE_DB_CONNECTION }}
      DISCORD_COVERAGE_URL: ${{ secrets.DISCORD_COVERAGE_URL }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: .next/
        retention-days: 14

  coverage:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/staging'

    env:
      NEXT_PUBLIC_SPOTIFY_WEB_CLIENT_ID: ${{ secrets.SPOTIFY_WEB_CLIENT_ID }}
      NEXT_PUBLIC_SPOTIFY_WEB_CLIENT_SECRET: ${{ secrets.SPOTIFY_WEB_CLIENT_SECRET }}
      NEXTAUTH_SECRET: test-secret-for-ci
      NEXTAUTH_URL: http://localhost:3000
      SUPABASE_DB_CONNECTION: ${{ secrets.SUPABASE_DB_CONNECTION }}
      DISCORD_COVERAGE_URL: ${{ secrets.DISCORD_COVERAGE_URL }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests with coverage
      run: npm test -- --coverage

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload test coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage/
        retention-days: 14

    - name: Send coverage webhook
      if: always()
      run: |
        # Parse coverage summary
        if [ -f coverage/coverage-summary.json ]; then
          COVERAGE_DATA=$(cat coverage/coverage-summary.json)
          
          # Send to external webhook if configured
          if [ -n "${{ secrets.COVERAGE_WEBHOOK_URL }}" ]; then
            curl -X POST "${{ secrets.COVERAGE_WEBHOOK_URL }}" \
              -H "Content-Type: application/json" \
              -d "{
                \"repository\": \"${{ github.repository }}\",
                \"branch\": \"${{ github.ref_name }}\",
                \"commit\": \"${{ github.sha }}\",
                \"coverage\": $COVERAGE_DATA,
                \"workflow_run_id\": \"${{ github.run_id }}\",
                \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"
              }"
          fi
          
          # Send to internal API (if this is a deployed environment)
          if [ -n "${{ secrets.DEPLOYMENT_URL }}" ]; then
            curl -X POST "${{ secrets.DEPLOYMENT_URL }}/api/coverage" \
              -H "Content-Type: application/json" \
              -d "{
                \"coverage\": $COVERAGE_DATA,
                \"metadata\": {
                  \"repository\": \"${{ github.repository }}\",
                  \"branch\": \"${{ github.ref_name }}\",
                  \"commit\": \"${{ github.sha }}\",
                  \"workflow_run_id\": \"${{ github.run_id }}\"
                }
              }"
          fi
        fi

    # Add a status check summary
    - name: Check Status
      if: always()
      run: |
        STATUS="${{ job.status }}"
        echo "Current job status: $STATUS"
        if [ "$STATUS" = "success" ]; then
          echo "✅ All checks passed!"
          exit 0
        else
          echo "❌ Some checks failed!"
          echo "Job status was: $STATUS"
          exit 1 